### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by lboklin** [tryton-vanmeer/SPCR-for-Steam#13]
Extension is installed and used to work, but as you can see below, nothing is shown. 
![Subnautica store page.](https://user-images.githubusercontent.com/6375669/52178010-25f16e80-27c9-11e9-9b77-f1452134c01f.png)

Edit: It shows the rating correctly in the wishlist, just not the store page.

**Comment by tryton-vanmeer** [comment]
Tested another game, as well as Subnautica. It appears to be working for me.

![image](https://user-images.githubusercontent.com/12022854/52178668-5e7c5280-279f-11e9-831a-fec86f80e363.png)

Is the extension updated to the latest version (1.3.1)?
What browser are you using?
Do you see any errors in the console (Assuming Firefox, Ctrl+Shift+k)?

**Comment by lboklin** [comment]
Firefox 65.0
Addon is 1.3.1
The console only has this possibly relevant message:
```
