### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by tryton-vanmeer** [tryton-vanmeer/SPCR-for-Steam#6]
+ Make necessary changes to code so that extension works in Chromium-based browsers
+ Release on chrome web store

**Comment by tryton-vanmeer** [comment]
Now on the [Chrome Web Store](https://chrome.google.com/webstore/detail/spcr-for-steam/emmcoldocnolgakkbigkjjfabjpenkla)!

**Comment by jvschiavo** [comment]
Do you guys know why this was taken down from Chrome Web Store?

**Comment by jvschiavo** [comment]
@tryton-vanmeer ?
