### ISSUE TITLE
Add a way to download the whole database

### ISSUE THREAD

**Issue by CreamyCookie** [tryton-vanmeer/SPCR-for-Steam#9]
Since the data was created by users for users, there should be a way to download the whole "Steam Play Compatibility Reports" database.

**Comment by tryton-vanmeer** [comment]
That's out of scope for this project and would be a feature of the upstream  [SPCR](https://spcr.netlify.com) project.

**Comment by bdefore** [comment]
@CreamyCookie ProtonDB now exports report submissions under the Open Database License https://www.protondb.com/news/report-exports-odbl
